// ═══════════════════════════════════════════════════════════
// Phase 42: Frontend Module Constants (mirror of backend)
// ═══════════════════════════════════════════════════════════

export interface FeatureDefinition {
    key: string;
    labelAr: string;
    isCore?: boolean; // لا يمكن تعطيلها
}

export interface ModuleDefinition {
    key: string;
    nameAr: string;
    nameEn: string;
    descriptionAr: string;
    icon: string;
    category: 'core' | 'legal' | 'finance' | 'productivity' | 'analytics' | 'management' | 'communication' | 'premium';
    isCore: boolean;
    isPremium?: boolean;
    features: FeatureDefinition[];
}

export const MODULES: Record<string, ModuleDefinition> = {
    dashboard: {
        key: 'dashboard',
        nameAr: 'لوحة المعلومات',
        nameEn: 'Dashboard',
        descriptionAr: 'لوحة تحكم شاملة تعرض ملخص عام لنشاط المكتب والإحصائيات الرئيسية',
        icon: 'LayoutDashboard',
        category: 'core',
        isCore: true,
        features: [
            { key: 'stats', labelAr: 'إحصائيات القضايا والعملاء', isCore: true },
            { key: 'upcoming_hearings', labelAr: 'الجلسات القادمة والمهام المعلقة' },
            { key: 'recent_activity', labelAr: 'آخر النشاطات والتحديثات' },
            { key: 'kpis', labelAr: 'مؤشرات الأداء الرئيسية' },
            { key: 'alerts', labelAr: 'إشعارات وتنبيهات مهمة', isCore: true },
        ],
    },
    cases: {
        key: 'cases',
        nameAr: 'القضايا',
        nameEn: 'Cases',
        descriptionAr: 'إدارة شاملة للقضايا القانونية مع تتبع كامل لدورة حياة القضية',
        icon: 'Briefcase',
        category: 'legal',
        isCore: false,
        features: [
            { key: 'create_edit', labelAr: 'إنشاء وتعديل القضايا' },
            { key: 'link_clients', labelAr: 'ربط القضايا بالعملاء والمحامين' },
            { key: 'track_status', labelAr: 'تتبع حالة القضية (جديدة، جارية، مغلقة)' },
            { key: 'workspace', labelAr: 'مساحة عمل القضية (مستندات، جلسات، مهام)' },
            { key: 'timeline', labelAr: 'التايم لاين والتحديثات' },
            { key: 'archive', labelAr: 'أرشفة وبحث القضايا' },
            { key: 'assign_team', labelAr: 'تعيين المحامين والفريق' },
        ],
    },
    clients: {
        key: 'clients',
        nameAr: 'العملاء',
        nameEn: 'Clients',
        descriptionAr: 'إدارة بيانات العملاء والتواصل معهم وتتبع قضاياهم وفواتيرهم',
        icon: 'Users',
        category: 'legal',
        isCore: false,
        features: [
            { key: 'create_edit', labelAr: 'إضافة وتعديل بيانات العملاء' },
            { key: 'profile', labelAr: 'ملف شامل لكل عميل' },
            { key: 'link_cases', labelAr: 'ربط العملاء بالقضايا والفواتير' },
            { key: 'search_filter', labelAr: 'البحث والفلترة المتقدمة' },
            { key: 'portal', labelAr: 'بوابة العميل (وصول محدود)' },
            { key: 'contact_log', labelAr: 'سجل التواصل والملاحظات' },
            { key: 'classify', labelAr: 'تصنيف العملاء (أفراد، شركات)' },
        ],
    },
    hearings: {
        key: 'hearings',
        nameAr: 'الجلسات',
        nameEn: 'Hearings',
        descriptionAr: 'متابعة وإدارة جلسات المحاكم مع تقويم متكامل وتنبيهات تلقائية',
        icon: 'Calendar',
        category: 'legal',
        isCore: false,
        features: [
            { key: 'schedule', labelAr: 'جدولة الجلسات وربطها بالقضايا' },
            { key: 'calendar', labelAr: 'تقويم تفاعلي بالعرض اليومي/الأسبوعي/الشهري' },
            { key: 'reminders', labelAr: 'تنبيهات قبل موعد الجلسة' },
            { key: 'results', labelAr: 'تسجيل نتائج الجلسات' },
            { key: 'assign_lawyer', labelAr: 'تعيين المحامي الحاضر' },
            { key: 'attachments', labelAr: 'مرفقات وملاحظات الجلسة' },
            { key: 'postponements', labelAr: 'تتبع التأجيلات' },
        ],
    },
    documents: {
        key: 'documents',
        nameAr: 'المستندات',
        nameEn: 'Documents',
        descriptionAr: 'نظام إدارة المستندات مع رفع وتنظيم وتصنيف الملفات',
        icon: 'FileText',
        category: 'legal',
        isCore: false,
        features: [
            { key: 'upload', labelAr: 'رفع وتحميل المستندات' },
            { key: 'classify', labelAr: 'تصنيف المستندات حسب النوع' },
            { key: 'link_cases', labelAr: 'ربط المستندات بالقضايا والعملاء' },
            { key: 'search', labelAr: 'البحث في المستندات' },
            { key: 'versioning', labelAr: 'إدارة الإصدارات' },
            { key: 'share', labelAr: 'مشاركة المستندات مع الفريق' },
            { key: 'multi_format', labelAr: 'دعم صيغ متعددة (PDF, Word, صور)' },
        ],
    },
    invoices: {
        key: 'invoices',
        nameAr: 'الفواتير',
        nameEn: 'Invoices',
        descriptionAr: 'إنشاء وإدارة الفواتير والمدفوعات مع تتبع الحالة المالية',
        icon: 'Receipt',
        category: 'finance',
        isCore: false,
        features: [
            { key: 'create', labelAr: 'إنشاء فواتير احترافية' },
            { key: 'link_cases', labelAr: 'ربط الفواتير بالقضايا والعملاء' },
            { key: 'track_payment', labelAr: 'تتبع حالة الدفع (مدفوعة، معلقة، متأخرة)' },
            { key: 'installments', labelAr: 'نظام أقساط مرن' },
            { key: 'export_pdf', labelAr: 'تصدير PDF للفواتير' },
            { key: 'revenue_reports', labelAr: 'تقارير الإيرادات والتحصيل' },
            { key: 'auto_notifications', labelAr: 'إشعارات الدفع التلقائية' },
        ],
    },
    tasks: {
        key: 'tasks',
        nameAr: 'المهام',
        nameEn: 'Tasks',
        descriptionAr: 'نظام إدارة المهام مع تعيين وتتبع وتنبيهات للفريق',
        icon: 'CheckSquare',
        category: 'productivity',
        isCore: false,
        features: [
            { key: 'create_assign', labelAr: 'إنشاء وتعيين المهام' },
            { key: 'priority_deadline', labelAr: 'تحديد أولويات ومواعيد نهائية' },
            { key: 'track_status', labelAr: 'تتبع حالة المهمة' },
            { key: 'link_cases', labelAr: 'ربط المهام بالقضايا' },
            { key: 'comments', labelAr: 'تعليقات ومناقشات على المهام' },
            { key: 'notifications', labelAr: 'إشعارات تلقائية' },
        ],
    },
    reports: {
        key: 'reports',
        nameAr: 'التقارير والتحليلات',
        nameEn: 'Reports & Analytics',
        descriptionAr: 'تقارير تفصيلية وتحليلات أداء شاملة مع إمكانية التصدير',
        icon: 'BarChart2',
        category: 'analytics',
        isCore: false,
        features: [
            { key: 'lawyer_performance', labelAr: 'تقرير أداء المحامين' },
            { key: 'case_stats', labelAr: 'إحصائيات القضايا حسب النوع والحالة' },
            { key: 'financial', labelAr: 'تقارير مالية (إيرادات، مصروفات)' },
            { key: 'hearings_attendance', labelAr: 'تقرير الجلسات والحضور' },
            { key: 'export', labelAr: 'تصدير التقارير (Excel, PDF)' },
            { key: 'charts', labelAr: 'رسوم بيانية تفاعلية' },
            { key: 'time_comparison', labelAr: 'مقارنات زمنية (شهري، سنوي)' },
        ],
    },
    team: {
        key: 'team',
        nameAr: 'الفريق',
        nameEn: 'Team',
        descriptionAr: 'إدارة أعضاء الفريق والأدوار والصلاحيات',
        icon: 'UserCog',
        category: 'management',
        isCore: false,
        features: [
            { key: 'manage_users', labelAr: 'إضافة وإدارة المستخدمين' },
            { key: 'assign_roles', labelAr: 'تعيين الأدوار (مالك، إداري، محامي، سكرتير)' },
            { key: 'permissions', labelAr: 'نظام صلاحيات مرن' },
            { key: 'toggle_accounts', labelAr: 'تعطيل/تفعيل الحسابات' },
            { key: 'activity_log', labelAr: 'سجل نشاط المستخدمين' },
        ],
    },
    messages: {
        key: 'messages',
        nameAr: 'الرسائل والتواصل',
        nameEn: 'Messages & Communication',
        descriptionAr: 'نظام مراسلات داخلي ودردشة فورية بين أعضاء الفريق',
        icon: 'MessageSquare',
        category: 'communication',
        isCore: false,
        features: [
            { key: 'internal_messages', labelAr: 'رسائل داخلية بين المستخدمين' },
            { key: 'live_chat', labelAr: 'دردشة فورية' },
            { key: 'file_attach', labelAr: 'إرفاق ملفات في الرسائل' },
            { key: 'notifications', labelAr: 'إشعارات الرسائل الجديدة' },
            { key: 'archive', labelAr: 'أرشفة المحادثات' },
            { key: 'search', labelAr: 'البحث في الرسائل' },
        ],
    },
    accounting: {
        key: 'accounting',
        nameAr: 'المحاسبة',
        nameEn: 'Accounting',
        descriptionAr: 'نظام محاسبي متكامل مع شجرة حسابات وقيود يومية وتقارير مالية',
        icon: 'Calculator',
        category: 'finance',
        isCore: false,
        features: [
            { key: 'chart_of_accounts', labelAr: 'شجرة حسابات كاملة' },
            { key: 'journal_entries', labelAr: 'قيود يومية (قيد مفرد/مركب)' },
            { key: 'general_ledger', labelAr: 'دفتر الأستاذ العام' },
            { key: 'trial_balance', labelAr: 'ميزان المراجعة' },
            { key: 'expenses_revenue', labelAr: 'إدارة المصروفات والإيرادات' },
            { key: 'financial_reports', labelAr: 'تقارير مالية (أرباح وخسائر، ميزانية)' },
            { key: 'cost_centers', labelAr: 'مراكز تكلفة' },
            { key: 'invoice_sync', labelAr: 'ربط مع الفواتير تلقائياً' },
        ],
    },
    hr: {
        key: 'hr',
        nameAr: 'الموارد البشرية',
        nameEn: 'HR Management',
        descriptionAr: 'إدارة شؤون الموظفين من حضور وانصراف وإجازات ورواتب',
        icon: 'UsersRound',
        category: 'management',
        isCore: false,
        features: [
            { key: 'employee_records', labelAr: 'سجل الموظفين الكامل' },
            { key: 'attendance', labelAr: 'نظام الحضور والانصراف' },
            { key: 'leaves', labelAr: 'إدارة الإجازات (سنوية، مرضية، طارئة)' },
            { key: 'payroll', labelAr: 'مسيّرات الرواتب' },
            { key: 'deductions_allowances', labelAr: 'حساب الاستقطاعات والبدلات' },
            { key: 'hr_reports', labelAr: 'تقارير HR شاملة' },
            { key: 'contracts', labelAr: 'عقود العمل وإدارة المستندات' },
        ],
    },
    forms: {
        key: 'forms',
        nameAr: 'النماذج الذكية',
        nameEn: 'Smart Forms',
        descriptionAr: 'إنشاء نماذج قانونية ذكية قابلة للتخصيص مع تعبئة تلقائية',
        icon: 'ClipboardList',
        category: 'premium',
        isCore: false,
        isPremium: true,
        features: [
            { key: 'drag_drop_builder', labelAr: 'محرر نماذج سحب وإفلات' },
            { key: 'templates', labelAr: 'قوالب جاهزة (توكيل، عقد، طلب)' },
            { key: 'auto_fill', labelAr: 'تعبئة تلقائية من بيانات العميل/القضية' },
            { key: 'dynamic_fields', labelAr: 'حقول ديناميكية ومشروطة' },
            { key: 'export_pdf', labelAr: 'تصدير PDF احترافي' },
            { key: 'share_clients', labelAr: 'مشاركة النماذج مع العملاء' },
            { key: 'archive', labelAr: 'أرشيف النماذج المعبأة' },
        ],
    },
    call_center: {
        key: 'call_center',
        nameAr: 'مركز الاتصالات',
        nameEn: 'Call Center',
        descriptionAr: 'نظام سنترال متكامل مع تسجيل المكالمات وإدارة خطوط الاتصال',
        icon: 'Phone',
        category: 'premium',
        isCore: false,
        isPremium: true,
        features: [
            { key: 'voip_integration', labelAr: 'ربط مع أنظمة VoIP/SIP' },
            { key: 'call_recording', labelAr: 'تسجيل المكالمات الواردة والصادرة' },
            { key: 'call_log', labelAr: 'سجل المكالمات مع التاريخ والمدة' },
            { key: 'call_transfer', labelAr: 'تحويل المكالمات بين الموظفين' },
            { key: 'ivr', labelAr: 'إعدادات الرد الآلي IVR' },
            { key: 'call_reports', labelAr: 'تقارير المكالمات والأداء' },
            { key: 'link_clients', labelAr: 'ربط المكالمات بالعملاء والقضايا' },
        ],
    },
    whatsapp: {
        key: 'whatsapp',
        nameAr: 'واتساب',
        nameEn: 'WhatsApp',
        descriptionAr: 'تكامل مع واتساب للتواصل المباشر مع العملاء من داخل النظام',
        icon: 'MessageCircle',
        category: 'premium',
        isCore: false,
        isPremium: true,
        features: [
            { key: 'connect_number', labelAr: 'ربط رقم واتساب المكتب' },
            { key: 'send_receive', labelAr: 'إرسال واستقبال الرسائل من النظام' },
            { key: 'templates', labelAr: 'قوالب رسائل جاهزة' },
            { key: 'bulk_messages', labelAr: 'إرسال رسائل جماعية' },
            { key: 'auto_notifications', labelAr: 'إشعارات تلقائية للعملاء' },
            { key: 'archive', labelAr: 'أرشيف المحادثات' },
            { key: 'link_cases', labelAr: 'ربط المحادثات بالقضايا والعملاء' },
        ],
    },
    legal_ai: {
        key: 'legal_ai',
        nameAr: 'البحث القانوني الذكي',
        nameEn: 'Legal AI Search',
        descriptionAr: 'محرك بحث قانوني مدعوم بالذكاء الاصطناعي في الأنظمة واللوائح',
        icon: 'Sparkles',
        category: 'premium',
        isCore: false,
        isPremium: true,
        features: [
            { key: 'ai_search', labelAr: 'بحث ذكي بالذكاء الاصطناعي' },
            { key: 'regulations_search', labelAr: 'البحث في الأنظمة واللوائح السعودية' },
            { key: 'suggestions', labelAr: 'اقتراحات مواد قانونية ذات صلة' },
            { key: 'summarize', labelAr: 'تلخيص المواد القانونية' },
            { key: 'compare', labelAr: 'المقارنة بين النصوص القانونية' },
            { key: 'bookmarks', labelAr: 'حفظ نتائج البحث المفضلة' },
            { key: 'link_cases', labelAr: 'ربط النتائج بالقضايا' },
        ],
    },
    legal_library: {
        key: 'legal_library',
        nameAr: 'المكتبة القانونية',
        nameEn: 'Legal Library',
        descriptionAr: 'مكتبة شاملة للأنظمة واللوائح والتعاميم القانونية السعودية',
        icon: 'BookOpen',
        category: 'legal',
        isCore: false,
        features: [
            { key: 'regulations', labelAr: 'الأنظمة السعودية الرسمية' },
            { key: 'executive_regs', labelAr: 'اللوائح التنفيذية' },
            { key: 'circulars', labelAr: 'التعاميم والقرارات الوزارية' },
            { key: 'glossary', labelAr: 'المعجم القانوني (عربي/إنجليزي)' },
            { key: 'categorize', labelAr: 'تصنيف حسب الجهة والموضوع' },
            { key: 'full_text_search', labelAr: 'البحث النصي الكامل' },
            { key: 'auto_updates', labelAr: 'تحديثات تلقائية للأنظمة الجديدة' },
        ],
    },
    legal_documents: {
        key: 'legal_documents',
        nameAr: 'محرر المستندات القانونية',
        nameEn: 'Legal Document Editor',
        descriptionAr: 'محرر نصوص متقدم لإعداد المذكرات والعقود والوثائق القانونية',
        icon: 'FileText',
        category: 'legal',
        isCore: false,
        features: [
            { key: 'rich_editor', labelAr: 'محرر نصوص غني (Rich Text)' },
            { key: 'memo_templates', labelAr: 'قوالب مذكرات جاهزة' },
            { key: 'contract_templates', labelAr: 'قوالب عقود احترافية' },
            { key: 'auto_fill', labelAr: 'تعبئة تلقائية لبيانات القضية/العميل' },
            { key: 'export', labelAr: 'تصدير Word/PDF' },
            { key: 'e_signature', labelAr: 'التوقيع الإلكتروني' },
            { key: 'share_drafts', labelAr: 'مشاركة المسودات مع الفريق' },
            { key: 'track_changes', labelAr: 'تتبع التعديلات' },
        ],
    },
    marketing: {
        key: 'marketing',
        nameAr: 'التسويق',
        nameEn: 'Marketing',
        descriptionAr: 'أدوات تسويقية متكاملة لاستقطاب العملاء وإدارة الحملات',
        icon: 'Megaphone',
        category: 'premium',
        isCore: false,
        isPremium: true,
        features: [
            { key: 'leads', labelAr: 'إدارة العملاء المحتملون (Leads)' },
            { key: 'source_tracking', labelAr: 'تتبع مصادر العملاء' },
            { key: 'campaigns', labelAr: 'حملات تسويقية' },
            { key: 'telemarketing', labelAr: 'التسويق عبر الهاتف' },
            { key: 'affiliate', labelAr: 'نظام التسويق بالعمولة' },
            { key: 'ad_analytics', labelAr: 'تحليلات نتائج الإعلانات' },
            { key: 'bulk_messaging', labelAr: 'رسائل جماعية (SMS, Email)' },
            { key: 'content_calendar', labelAr: 'تقويم المحتوى التسويقي' },
        ],
    },
    settings: {
        key: 'settings',
        nameAr: 'الإعدادات',
        nameEn: 'Settings',
        descriptionAr: 'إعدادات النظام والملف الشخصي والإشعارات',
        icon: 'Settings',
        category: 'core',
        isCore: true,
        features: [
            { key: 'profile', labelAr: 'الملف الشخصي', isCore: true },
            { key: 'notifications_config', labelAr: 'إعدادات الإشعارات', isCore: true },
            { key: 'call_center_config', labelAr: 'إعدادات السنترال' },
            { key: 'team_permissions', labelAr: 'إدارة الفريق والصلاحيات' },
            { key: 'office_config', labelAr: 'إعدادات المكتب العامة' },
        ],
    },
};

// Category labels for grouping in SA UI
export const CATEGORY_LABELS: Record<string, { ar: string; en: string }> = {
    core: { ar: 'أساسي', en: 'Core' },
    legal: { ar: 'قانوني', en: 'Legal' },
    finance: { ar: 'مالي', en: 'Finance' },
    productivity: { ar: 'إنتاجية', en: 'Productivity' },
    analytics: { ar: 'تحليلات', en: 'Analytics' },
    management: { ar: 'إدارة', en: 'Management' },
    communication: { ar: 'تواصل', en: 'Communication' },
    premium: { ar: 'متقدم', en: 'Premium' },
};
